cat("Statistika Deskriptif(Y)\n")
summary(data$Y)
cat("Statistika Deskriptif(X1)\n")
summary(data$X1)
cat("Statistika Deskriptif(X2)\n")
summary(data$X2)
cat("Statistika Deskriptif(X3)\n")
summary(data$X3)
cat("Statistika Deskriptif(X4)\n")
summary(data$X4)
cat("Statistika Deskriptif(X5)\n")
summary(data$X5)